#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return



    
# Shortcuts
alias python='python2.7'
alias android='sh /home/deepakchethan/android-studio/bin/studio.sh'
alias ls='ls --color'
alias ll='ls -l --color'
alias la='ls -al --color'
alias arduino='sudo sh /home/deepakchethan/arduino-1.8.2/arduino'
alias wifi='sudo wifi-menu'
alias vpn='sudo openvpn --config /etc/vpnbook/vpnbook-fr1-tcp80.ovpn'
alias def="/usr/bin/sdcv"
alias javec="cd /opt/eclipse && ./eclipse"

# Exports
export PS1='at \w >\[\033[0m\] '
export VISUAL="vim"
export TERM=xterm-256color
export EDITOR="vim"

PATH=$PATH:/home/deepakchethan/.gem/ruby/2.5.0/bin

# VIM bindings to cmdline
set -o vi


