#!/bin/bash
#This was made to make sure all my .rc files are updated
#check if the git director exists

if [ -d ~/Git/Config ]
then
    echo  "The Git/Config directory exists"
else
    echo "Git directory doesnt exist"
    echo "Want me to make one for you ?[y/n]"
    read ans
    if [ ans =  'y' ]
    then
	mkdir -vp ~/Git/Config
    fi
fi

#mov the contents to there respective folders

if [ -f ~/.vimrc ]
then
 mkdir -p ~/Git/Config/Vimrc
 cp ~/.vimrc ~/Git/Config/Vimrc
 echo "Copied vimrc file"
fi

if [ -f ~/.bashrc ]
then
  mkdir -p ~/Git/Config/Bashrc
  cp ~/.bashrc ~/Git/Config/Bashrc
  cp ~/.bash_profile ~/Git/Config/Bashrc
  echo "Copied bash config files"
fi

if [ -f ~/.config/i3/config ]
then
  mkdir -p ~/Git/Config/i3/
  cp ~/.config/i3/config ~/Git/Config/i3/
  echo "Copied i3 config file"
fi

#if [ -d ~/.config/fish ]
#then
#  mkdir -p ~/Git/Config/fish/
#  cp -r ~/.config/fish/* ~/Git/Config/fish/
#  echo "Copied Fish shell config file"
#fi

if [ -d ~/.tmuxinator ]
then
  mkdir -p ~/Git/Config/Tmuxinator/
  cp -r ~/.tmuxinator ~/Git/Config/Tmuxinator/
  echo "Copied tmuxinator session files"
fi

if [ -d ~/.irssi ]
then
  mkdir -p ~/Git/Config/Irssi/
  cp -r ~/.irssi ~/Git/Config/Irssi/
  echo "Copied Irssi config files"
fi

if [[ -f ~/.gmail_muttrc && -f ~/.outlook_muttrc ]]
then
    mkdir -p ~/Git/Config/Mutt/
    cp ~/.gmail_muttrc ~/Git/Config/Mutt/
    cp ~/.outlook_muttrc ~/Git/Config/Mutt/
    echo "Copied your Mutt files"
fi

if [ -f ~/.config/i3/i3blocks.conf ]
then
  mkdir -p ~/Git/Config/i3/
  cp -r ~/.config/i3/i3blocks.conf ~/Git/Config/i3/
  echo "Copied i3blocks config file"
fi

if [ -f ~/.Xresources ]
then
  mkdir -p ~/Git/Config/Xresources
  cp ~/.Xresources ~/Git/Config/Xresources/
  echo "Copied xresources file"
fi

if [ -f /etc/X11/xorg.conf.d/70-synaptics.conf ]
then
   mkdir -p ~/Git/Config/Synaptics 
   cp /etc/X11/xorg.conf.d/70-synaptics.conf ~/Git/Config/Synaptics/
   echo "Copied the synaptics file"
fi


if [ -f ~/.tmux.conf ]
then
  mkdir -p ~/Git/Config/Tmux
  cp ~/.tmux.conf ~/Git/Config/Tmux
  echo "Copied tmux.conf file"
fi

if [ -d /usr/lib/i3blocks ]
then 
   cp -rf /usr/lib/i3blocks ~/Git/Config
   echo "Copied your blocks for i3"
fi

if [[ -f ~/.emacs.d/init.el  &&  -f ~/.emacs ]]
then
    mkdir -p ~/Git/Config/Emacs
    sudo cp -fr ~/.emacs.d/init.el ~/Git/Config/Emacs/
    cp ~/.emacs ~/Git/Config/Emacs/
    echo "Copied emacs config files"
fi

echo "Change the password of muttrc files"
vim ~/Git/Config/Mutt/.gmail_muttrc
vim ~/Git/Config/Mutt/.outlook_muttrc




echo "Your files are preserved in ~/Git/Config folder!"


