#!/bin/bash

#This is to move all the folders . files cloned from github

#copy the .rcs

PREF=$1

if [ -z "$PREF" ];
then
    echo "Need the source!"
    exit
fi

cp $(PREF)/Vimrc/vimrc ~/.vimrc && echo "Copied .vimrc file"

cp $(PREF)/Bashrc/bashrc ~/.bashrc && cp $(PREF)/Bashrc/bash_profile ~/.bach_profile && echo "Copied bash files"

mkdir -p ~/.config/i3/ && cp $(PREF)/i3/* ~/.config/i3/ && echo "Copied i3 config and blocks.conf  file"

cp $(PREF)/Xresources/Xresources ~/.Xresources && echo "Copied .Xresources file"

cp $(PREF)/Tmux/tmux.conf ~/.tmux.conf && echo "Copied tmux.conf file"

cp -r $(PREF)/Irssi/irssi ~/.irssi && echo "Copied the Irssi config files"

sudo cp -r $(PREF)/i3blocks /usr/lib/ && echo "Copied the blocks"

sudo cp $(PREF)/Synaptics/* /etc/X11/xorg.conf.d/ && echo "Copied the synaptics file"

sudo cp -r $(PREF)/Emacs/init.el ~/.emacs.d && sudo cp $(PREF)/Emacs/emacs  ~/.emacs && echo "Copied the emacs config files"

sudo cp $(PREF)/Mutt/gmail_muttrc ~/.gmail_muttrc && sudo cp $(PREF)/Mutt/outlook_muttrc ~/.outlook_muttrc && echo "Copied the Mutt files"
















